// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file bilibili.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili.proto.
 */
export const file_bilibili: GenFile = /*@__PURE__*/
  fileDesc("Cg5iaWxpYmlsaS5wcm90byItCg5EYW5tYWt1U2VnbWVudBIbCgVlbGVtcxgBIAMoCzIMLkRhbm1ha3VFbGVtItgBCgtEYW5tYWt1RWxlbRIKCgJpZBgBIAEoAxIQCghwcm9ncmVzcxgCIAEoBRIMCgRtb2RlGAMgASgFEhAKCGZvbnRzaXplGAQgASgFEg0KBWNvbG9yGAUgASgNEhAKCG1pZF9oYXNoGAYgASgJEg8KB2NvbnRlbnQYByABKAkSDQoFY3RpbWUYCCABKAMSDgoGd2VpZ2h0GAkgASgFEg4KBmFjdGlvbhgKIAEoCRIMCgRwb29sGAsgASgFEg4KBmlkX3N0chgMIAEoCRIMCgRhdHRyGA0gASgFYgZwcm90bzM");

/**
 * @generated from message DanmakuSegment
 */
export type DanmakuSegment = Message<"DanmakuSegment"> & {
  /**
   * @generated from field: repeated DanmakuElem elems = 1;
   */
  elems: DanmakuElem[];
};

/**
 * Describes the message DanmakuSegment.
 * Use `create(DanmakuSegmentSchema)` to create a new message.
 */
export const DanmakuSegmentSchema: GenMessage<DanmakuSegment> = /*@__PURE__*/
  messageDesc(file_bilibili, 0);

/**
 * @generated from message DanmakuElem
 */
export type DanmakuElem = Message<"DanmakuElem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int32 progress = 2;
   */
  progress: number;

  /**
   * @generated from field: int32 mode = 3;
   */
  mode: number;

  /**
   * @generated from field: int32 fontsize = 4;
   */
  fontsize: number;

  /**
   * @generated from field: uint32 color = 5;
   */
  color: number;

  /**
   * @generated from field: string mid_hash = 6;
   */
  midHash: string;

  /**
   * @generated from field: string content = 7;
   */
  content: string;

  /**
   * @generated from field: int64 ctime = 8;
   */
  ctime: bigint;

  /**
   * @generated from field: int32 weight = 9;
   */
  weight: number;

  /**
   * @generated from field: string action = 10;
   */
  action: string;

  /**
   * @generated from field: int32 pool = 11;
   */
  pool: number;

  /**
   * @generated from field: string id_str = 12;
   */
  idStr: string;

  /**
   * @generated from field: int32 attr = 13;
   */
  attr: number;
};

/**
 * Describes the message DanmakuElem.
 * Use `create(DanmakuElemSchema)` to create a new message.
 */
export const DanmakuElemSchema: GenMessage<DanmakuElem> = /*@__PURE__*/
  messageDesc(file_bilibili, 1);

